=== Alex29ec/EjerciciosLMSGI/examenresuelto/cocteleria.dtd
<!ELEMENT cocteleria (cocteles, ofertas)>
<!ELEMENT cocteles (coctel+)>
<!ELEMENT ofertas (oferta*)>
<!ELEMENT coctel (nombre, Alcohol?, precio, (existencias | agotado))>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT Alcohol EMPTY>
<!ELEMENT precio EMPTY>
<!ELEMENT existencias EMPTY>
<!ELEMENT agotado EMPTY>
<!ELEMENT oferta (#PCDATA | coctelReferido)*>
<!ELEMENT coctelReferido ANY>
<!ATTLIST cocteleria direccion CDATA #IMPLIED 
                      nombre CDATA #REQUIRED
                      telefono CDATA #FIXED "957765498">
<!ATTLIST coctel codigo ID #REQUIRED
                 ingredientePrincipal (Coca-Cola | Fanta | 7Up) "Fanta">
<!ATTLIST coctelReferido codigoCoctel IDREF #REQUIRED
                         Combinado IDREFS #IMPLIED>
<!ENTITY % atributoCoste "coste CDATA #IMPLIED"> 
<!ATTLIST precio %atributoCoste;>
<!ATTLIST oferta %atributoCoste;>
<!ENTITY limon "limon extra">

=== Alex29ec/EjerciciosLMSGI/examenresuelto/cocteleria.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cocteleria SYSTEM "cocteleria.dtd">
<cocteleria direccion="Calle el taquito" nombre="El tacazo" telefono="957765498">
  <cocteles>
    <coctel codigo="RC" ingredientePrincipal="Coca-Cola">
      <nombre>Ron-Cola</nombre>
      <Alcohol/>
      <precio coste="6" />
      <existencias />
    </coctel>
    <coctel codigo="alisio">
      <nombre>ALISIOS DE PASIÃ“N con &limon;</nombre>
      <precio coste="5" />
      <agotado />
    </coctel>
  </cocteles>
  <ofertas>
    <oferta coste="15">2x1 
      <coctelReferido codigoCoctel="RC" Combinado="RC alisio" />
    </oferta>
  </ofertas>
</cocteleria>
